export enum LocationType { // TODO change these types!
    SPORTS = 'Sports',
    FOOD = 'Food',
    GOLF = 'Golf',
    ICE_HOCKEY = 'Ice Hockey',
    MMA = 'Mixed Martial Arts',
    RUGBY = 'Rugby',
    SAILING = 'Sailing',
    SKIING = 'Skiing',
    SNOWBOARDING = 'Snowboarding',
    SOCCER = 'Soccer',
    SQUASH = 'Squash',
    SWIMMING = 'Swimming',
    TABLE_TENNIS = 'Table Tennis',
    TENNIS = 'Tennis',
    VOLLEYBALL = 'Volleyball',
    WRESTLING = 'Wrestling',
    WATER_POLO = 'Water Polo',
}