export enum LocationType { // TODO change these types!
    ATHLETICS = 'Athletics', //General type, we'll change this later
    BADMINTON = 'Badminton', // Followed by the other types of locations... that we'll change...
    BASEBALL = 'Baseball',
    BASKETBALL = 'Basketball',
    BOXING = 'Boxing',
    CRICKET = 'Cricket',
    CYCLING = 'Cycling',
    FUTSOL = 'Futsol',
    GOLF = 'Golf',
    ICE_HOCKEY = 'Ice Hockey',
    MMA = 'Mixed Martial Arts',
    RUGBY = 'Rugby',
    SAILING = 'Sailing',
    SKIING = 'Skiing',
    SNOWBOARDING = 'Snowboarding',
    SOCCER = 'Soccer',
    SQUASH = 'Squash',
    SWIMMING = 'Swimming',
    TABLE_TENNIS = 'Table Tennis',
    TENNIS = 'Tennis',
    VOLLEYBALL = 'Volleyball',
    WRESTLING = 'Wrestling',
    WATER_POLO = 'Water Polo',
}